name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  schedule:
    # NOTE: UTCなので9時間引く
    # 毎週土曜日の午前9時に実行
    - cron: 0 0 * * 6
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version-file: .tool-versions
        cache: yarn

    - name: Install dependencies
      run: yarn install

    - name: Lint
      run: yarn lint

  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version-file: .tool-versions
        cache: yarn

    - name: Install dependencies
      run: yarn install

    - name: Test
      run: yarn test-coverage

  generate:
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version-file: .tool-versions
        cache: yarn

    - name: Install dependencies
      run: yarn install

    - name: Generate feed
      run: yarn feed-generate

    - name: Generate site
      run: yarn site-build

    - name: Archive feed
      uses: actions/upload-artifact@v4
      with:
        name: feed-generate-results
        path: public/feeds
